nav:
  - index.md
  - Overview:
      - getting-started.md
      - custom-functions.md
      - versioning.md
  - CLI:
      - cli/getting-started.md
      - cli/examples.md
      - cli/usage-tips.md
      - cli/env-vars.md
      - cli/reference.md
  - Client:
      - client/getting-started.md
      - client/response-types.md
      - client/session-management.md
      - Reference:
          - client/reference/client.md
          - client/reference/*
  - About:
      - credits.md
      - contributing.md
