nav:
  - index.md
  - Overview:
      - overview/getting-started.md
      - overview/custom-functions.md
      - overview/versioning.md
  - CLI:
      - cli/getting-started.md
      - cli/examples.md
      - cli/usage-tips.md
      - cli/env-vars.md
      - cli/reference.md
  - Client:
      - client/getting-started.md
      - client/response-types.md
      - client/session-management.md
      - Reference:
          - client/reference/client.md
          - API:
              - client/reference/api/*
          - Wrapper:
              - client/reference/wrapper/*
  - Info:
      - info/credits.md
      - info/contributing.md
      - info/development.md
